-- DANGER: This will permanently delete sales history and product/inventory data.
-- Target DB: migunani_motor_db (or whatever DB_NAME points to)
--
-- Recommended flow:
-- 1) Take a backup first (mysqldump).
-- 2) Stop app writes (pause back_end/front_end if needed).
-- 3) Run this script via mysql client.

SET FOREIGN_KEY_CHECKS = 0;

-- Sales / transactions
TRUNCATE TABLE pos_sale_items;
TRUNCATE TABLE pos_sales;

TRUNCATE TABLE delivery_handover_items;
TRUNCATE TABLE delivery_handovers;

TRUNCATE TABLE retur_handover_items;
TRUNCATE TABLE retur_handovers;
TRUNCATE TABLE returs;

TRUNCATE TABLE invoice_cost_overrides;
TRUNCATE TABLE invoice_items;
TRUNCATE TABLE invoices;

TRUNCATE TABLE order_allocations;
TRUNCATE TABLE order_events;
TRUNCATE TABLE order_issues;
TRUNCATE TABLE order_items;
TRUNCATE TABLE orders;

-- Finance entries that are typically generated by sales flows
TRUNCATE TABLE journal_lines;
TRUNCATE TABLE journals;

TRUNCATE TABLE cod_collections;
TRUNCATE TABLE cod_settlements;
TRUNCATE TABLE driver_balance_adjustments;
TRUNCATE TABLE driver_debt_adjustments;
TRUNCATE TABLE customer_balance_entries;

-- Optional: clear carts (uncomment if desired)
TRUNCATE TABLE cart_items;
TRUNCATE TABLE carts;

-- Product / inventory (data produk yang dijual)
TRUNCATE TABLE clearance_promos;

TRUNCATE TABLE inventory_batch_consumptions;
TRUNCATE TABLE inventory_batch_reservations;
TRUNCATE TABLE inventory_batches;

TRUNCATE TABLE inventory_cost_ledger;
TRUNCATE TABLE stock_mutations;
TRUNCATE TABLE stock_opname_items;
TRUNCATE TABLE stock_opnames;
TRUNCATE TABLE product_cost_states;

TRUNCATE TABLE product_aliases;
TRUNCATE TABLE product_categories;
TRUNCATE TABLE products;

-- Optional: also reset categories (uncomment if you want to import categories from scratch too)
-- TRUNCATE TABLE categories;

SET FOREIGN_KEY_CHECKS = 1;
